language: python
python:
  - "3.6"

install:
  - pip install pandas
  - pip install numpy
  - pip install matplotlib
  - pip install seaborn
  - pip install coala

script:
  - echo "skipping tests"
  - coala --non-interactive