language: python
python:
  - "3.6"

install:
  - pip install pandas
  - pip install numpy
  - pip install matplotlib
  - pip install seaborn
  - pip install coala

script:
  - echo "skipping tests"
  - python setup.py bdist_wheel
  - pip install ./dist/coala-*.whl
  - curl -fsSL -o coala-bears.zip $BEARS_ZIP_URL/master
  - pip install coala-bears.zip[alldeps] --pre -U
  - coala --non-interactive